# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "Alpha 1.0"
  title: <Monopolly>

host: localhost:8080
schemes:
  - http

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /auth:
    # This is a HTTP operation
    post:
      # Describe this verb here. Note: you can use markdown
      summary: Authenticate
      description: |
        Authenticate a user
      # This is array of GET operation parameters:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        # An example parameter that is in query and is required
        -
          name: user
          in: body
          description: user to be connected
          required: true
          schema:
            $ref: '#/definitions/user'

      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Authentication sucessfull.
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            $ref: '#/definitions/token'
        400:
          description: Bad request.
        401:
          description: Bad credentials.

  /user:
    post:
      summary: new user
      description: |
        Creates a new user. Username and password shall not be emtpy.
      consumes:
        - application/json
      parameters:
        -
          name: user
          in: body
          description: user to be created
          required: true
          schema:
            $ref: '#/definitions/user'

      responses:
        201:
          description: Sucessfully created.
        400:
          description: Bad request.
        409:
          description: Already exists.

    delete:
      summary: delete user
      description: |
        Let a user delete himself
      parameters:
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string

      responses:
        204:
          description: user deleted successfully.
        400:
          description: invalid token or credentials.
        403:
          description: only you can delete yourself.

  /user/rooms:
    get:
      summary: Gets your rooms
      description: retrives a list of your rooms.
      produces:
        - application/json
      parameters:
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/completeRoom'
        400:
          description: Bad request.
        403:
          description: Forbidden.

  /rooms:
    post:
      summary: New room
      description: |
        Creates a new room
      consumes:
        - application/json
      parameters:
        - name: room
          in: body
          description: room to be created
          required: true
          schema:
            $ref: '#/definitions/room'
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string

      responses:
        201:
          description: Sucessfully created.
        400:
          description: Bad request.
        403:
          description: Forbidden.

  /rooms/{roomId}:
    patch:
      summary: Patches this room.
      description: Patches this room.
      parameters:
        - name: roomId
          in: path
          description: room to be modified
          required: true
          type: integer
          format: int64
        - name: room
          in: body
          description: room to be patched
          required: true
          schema:
            $ref: '#/definitions/room'
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string
      responses:
        200:
          description: OK
        401:
          description: You don't own this room.
        403:
          description: You don't have a token.
        404:
          description: not found.

    delete:
      summary: Deletes this room.
      description: Deletes this room.
      parameters:
        - name: roomId
          in: path
          description: room to be deleted
          required: true
          type: integer
          format: int64
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string
      responses:
        200:
          description: OK
        401:
          description: You don't own this room.
        403:
          description: You don't have a token.
        404:
          description: not found.

    get:
      summary: Gets this room.
      description: Gets this room. Rooms are visible by all.
      parameters:
        - name: roomId
          in: path
          description: room to be get
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/completeRoom'
        404:
          description: not found.

    post:
      summary: New poll
      description: |
        Creates a new poll
      consumes:
        - application/json
      parameters:
        - name: roomId
          in: path
          description: the room
          required: true
          type: integer
          format: int64
        - name: poll
          in: body
          description: poll to be created
          required: true
          schema:
            $ref: '#/definitions/poll'
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string
      responses:
        201:
          description: Sucessfully created.
        400:
          description: Bad request.
        403:
          description: Forbidden.

  /rooms/polls/{pId}:
    get:
      summary: Gets a poll
      description: |
        Returns the selected poll. This endpoint can be used without an authentification.
      produces:
        - application/json
      parameters:
        - name: pId
          in: path
          description: poll to be retrived
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: the requested poll
          schema:
            $ref: '#/definitions/completePoll'
        404:
          description: Not found.

    patch:
      summary: patches poll.
      description: patches this poll only if you owns it.
      parameters:
        - name: pId
          in: path
          description: the poll
          required: true
          type: integer
          format: int64
        - name: poll
          in: body
          description: the poll
          required: true
          schema:
            $ref: '#/definitions/poll'
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string
      responses:
        204:
          description: OK
        401:
          description: Unauthorized.
        403:
          description: Forbidden.
        404:
          description: Not found.

    delete:
      summary: deletes this poll.
      description: deletes this poll only if you owns it.
      parameters:
        - name: pId
          in: path
          description: the poll
          required: true
          type: integer
          format: int64
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string
      responses:
        204:
          description: OK
        401:
          description: Unauthorized.
        403:
          description: Forbidden.
        404:
          description: Not found.

  /rooms/{roomId}/polls/{pId}:
    post:
      summary: add a question
      description: adds a question to your poll
      consumes:
        - application/json
      parameters:
        - name: roomId
          in: path
          description: the room
          required: true
          type: integer
          format: int64
        - name: pId
          in: path
          description: the poll
          required: true
          type: integer
          format: int64
        - name: question
          in: body
          description: Question to be added
          required: true
          schema:
            $ref: '#/definitions/question'
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string

      responses:
        201:
          description: OK
        401:
          description: You don't own this poll.
        403:
          description: You don't have a token.


  /rooms/polls/question/{qId}:
    patch:
      summary: patch this question
      description: Update a question in your poll. If users are using it, they will be notified instantly via websocket.
      consumes:
        - application/json
      parameters:
        - name: qId
          in: path
          description: the question
          required: true
          type: integer
          format: int64
        - name: question
          in: body
          description: question to be patched
          required: true
          schema:
            $ref: '#/definitions/completeQuestion'
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string
      responses:
        200:
          description: OK.
        401:
          description: Unauthorized.
        403:
          description: Forbidden.
        404:
          description: Not found.

    delete:
      summary: deletes a question
      description: deletes a question of this poll
      parameters:
        - name: qId
          in: path
          description: poll to be retrived
          required: true
          type: integer
          format: int64
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string
      responses:
        200:
          description: OK

  /answer:
    post:
      summary: Posts an answer .
      description: Posts an answer for a question. If this question is closed then it is not possible any longer.
      parameters:
        - name: answer
          in: body
          description: The answer to be submitted.
          required: true
          schema:
            $ref: '#/definitions/CompleteAsnwer'
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          type: string
      responses:
        200:
          description: OK. Returns the question with the correct answer.
          schema:
            $ref: '#/definitions/completeQuestion'
        400:
          description: Invalid answer object.
        403:
          description: You don't have a token.
        404:
          description: Question not found.
        409:
          description: You already have submitted an answer.




definitions:
  user:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string

  token:
    type: object
    required:
      - token
    properties:
      token:
        type: string

  room:
    type: object
    required:
      - name
    properties:
      name:
        type: string

  completeRoom:
    type: object
    required:
      - id
      - owner
      - name
      - polls
    properties:
      id:
        type: integer
        format: int64
      owner:
        type: integer
        format: int64
      name:
        type: string
      polls:
        type: array
        items:
          $ref: '#/definitions/completePoll'

  poll:
    type: object
    required:
      - name
    properties:
      name:
        type: string

  completePoll:
    type: object
    required:
      - id
      - name
      - questions
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      questions:
        type: array
        items:
          $ref: '#/definitions/completeQuestion'

  question:
    type: object
    required:
      - body
    properties:
      body:
        type: string
      answers:
        type: array
        items:
          $ref: '#/definitions/asnwer'

  completeQuestion:
    type: object
    required:
      - id
      - body
      - answers
      - closed
    properties:
      id:
        type: integer
        format: int64
      body:
        type: string
      answers:
        type: array
        items:
          $ref: '#/definitions/CompleteAsnwer'
      closed:
        type: boolean

  asnwer:
    type: object
    required:
      - body
      - isValid
    properties:
      body:
        type: string
      isValid:
        type: boolean

  CompleteAsnwer:
    type: object
    required:
      - id
      - body
      - isValid
    properties:
      id:
        type: integer
        format: int64
      body:
        type: string
      isValid:
        type: boolean